/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './imageCropperModule';
import * as import2 from '@angular/common';
class ImageCropperModuleInjector extends import0.ɵNgModuleInjector<import1.ImageCropperModule> {
  _CommonModule_0:import2.CommonModule;
  _ImageCropperModule_1:import1.ImageCropperModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.ImageCropperModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ImageCropperModule_1 = new import1.ImageCropperModule();
    return this._ImageCropperModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.ImageCropperModule)) { return this._ImageCropperModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ImageCropperModuleNgFactory:import0.NgModuleFactory<import1.ImageCropperModule> = new import0.NgModuleFactory<any>(ImageCropperModuleInjector,import1.ImageCropperModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FuZ2VsL1Byb2plY3RzL0JURy9hbmd1bGFyMi1pbWctY3JvcHBlci9zcmMvaW1hZ2VDcm9wcGVyTW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FuZ2VsL1Byb2plY3RzL0JURy9hbmd1bGFyMi1pbWctY3JvcHBlci9zcmMvaW1hZ2VDcm9wcGVyTW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
